server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://mainline.proxy.rlwy.net:49676/trading_platofrm
    username: root
    password: hAFSMpYViCCbzqulXYKnXdVzdWgVJWdV
    driver-class-name: com.mysql.cj.jdbc.Driver