server:
  port: 8081

spring:
  application:
    name: user-management-service

  config:
    import: optional:configserver:https://config-server-production-9c39.up.railway.app

eureka:
  client:
    service-url:
      defaultZone: https://eureka-service-production-dbce.up.railway.app/eureka/
    register-with-eureka: true
    fetch-registry: true
