server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: user-auth-route
          uri: https://user-service-production-904c.up.railway.app
          predicates:
            - Path=/auth/**

        - id: user-management-route
          uri: https://user-service-production-904c.up.railway.app
          predicates:
            - Path=/api/users/**

        - id: product-farmer-route
          uri: https://product-service-production-b18f.up.railway.app
          predicates:
            - Path=/farmers/me/products/**

        - id: product-all-route
          uri: https://product-service-production-b18f.up.railway.app
          predicates:
            - Path=/api/products/**

        - id: product-retailer-route
          uri: https://product-service-production-b18f.up.railway.app
          predicates:
            - Path=/retailers/products/**

        - id: order-service-route
          uri: https://order-service-production-907e.up.railway.app
          predicates:
            - Path=/api/v1/retailers/me/orders/**

        - id: vms-user-auth-route
          uri: https://vms-user-service-production-b71e.up.railway.app
          predicates:
            - Path=/vms-api/api/auth/**
          filters:
            - StripPrefix=1

        - id: vms-user-route
          uri: https://vms-user-service-production-b71e.up.railway.app
          predicates:
            - Path=/vms-api/api/users/**
          filters:
            - StripPrefix=1

        - id: vms-event-route
          uri: https://vms-event-service-production.up.railway.app
          predicates:
            - Path=/vms-api/api/events/**
          filters:
            - StripPrefix=1

        - id: vms-participation-route
          uri: https://vms-event-service-production.up.railway.app
          predicates:
            - Path=/vms-api/api/participations/**
          filters:
            - StripPrefix=1

        - id: vms-feedback-route
          uri: https://vms-event-service-production.up.railway.app
          predicates:
            - Path=/vms-api/api/feedbacks/**
          filters:
            - StripPrefix=1

        - id: vms-notification-route
          uri: https://vms-notification-service-production.up.railway.app
          predicates:
            - Path=/vms-api/api/notifications/**
          filters:
            - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: https://eureka-service-production-dbce.up.railway.app/eureka/
    register-with-eureka: true
    fetch-registry: true
